name: Update my awesome README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '03 4 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node index.js
        env:
          CI: true
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Aecy
          author_email: devsnake@hotmail.com
          message: ':memo: README.md updated by Aecy'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
